services:
  dev-php:
    build:
      dockerfile: dev.Dockerfile
    init: true
    restart: unless-stopped
    volumes:
      - ./:/app
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  dev-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dev-mysql-data:/var/lib/mysql

volumes:
  dev-mysql-data:
