services:
  web:
    image: nginx:1-alpine
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/templates:ro
    ports:
      - 80:80

  php:
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
